### PR TITLE
Fix service error mapping on listing nonexistent container

### LINKED ISSUE #150: [BUG] 5xx error on not existent container or version
**Describe the bug**
5xx error is displayed by publisher on accessing not existent container or version

**To Reproduce**
1. `go generate -v ./... && goreleaser build --snapshot --clean && docker-compose build && docker-compose up || docker-compose down`
2. access via browser to any (not existent) container
3. create new container via archived-cli
4. access via browser to any (not existent) version

**Expected behavior**
Not existent entities must report 404 error

**Configuration file snippet**

doesn't matter, since reproduced right with [instruction in README](https://github.com/teran/archived/tree/95aa76bf6d6cf2c1cfc3f2812727fae55e1d1fb5?tab=readme-ov-file#local-development)

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by 71g3pf4c3**
Closes #150

### CODE REVIEW

**Comment by teran** [comment]
It looks like this part is about versions listing, right?

Since there's a gap on that fields would you mind to add some negative tests if they're not present just for the cases you're fixing?

Thanks.

File: publisher/presenter/html/handlers.go [hunk 1]
```diff
@@ -78,6 +78,10 @@ func (h *handlers) ContainerIndex(c echo.Context) error {
 
 	pagesCount, containers, err := h.svc.ListContainersByPage(c.Request().Context(), namespace, page)
 	if err != nil {
+		log.Warnf("%s", err)
```
Comment (teran) [inline publisher/presenter/html/handlers.go:81]: Here it would be good to describe were it come from i.e. what method, etc. and another thing here is it probably should be an Info level since in some cases 404 is expected code if there're some logic behind.

Comment (71g3pf4c3) [reply publisher/presenter/html/handlers.go]: Deleted that log point, needed just for debugging

**Review by teran — APPROVED** [review]
